stages:
  - test
  - cover

test_10:
  image: node:10
  stage: test
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm install
    - npm test
  tags:
    - docker
  artifacts:
    paths:
      - coverage

coveralls:
  image: node:10
  dependencies:
    - test_10
  stage: cover
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm install
    - npm run coveralls
  tags:
    - docker
  artifacts:
    paths:
      - coverage
