stages:
  - test
  - cover
  - release

test:
  image: node:10
  stage: test
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm ci
    - npm test
  tags:
    - docker
  artifacts:
    paths:
      - coverage

coveralls:
  image: node:10
  dependencies:
    - test
  stage: cover
  only:
    - dev
  # don't run coverage when merging release back into dev
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\d+.\d+.\d+$/
      - $CI_COMMIT_BEFORE_SHA =~ /^\d+.\d+.\d+$/
      - $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/
      - $CI_COMMIT_TITLE =~ /^\d+.\d+.\d+$/
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm ci
    - npm run coveralls
  tags:
    - docker
  artifacts:
    paths:
      - coverage

release:
  image: node:10
  dependencies:
    - coveralls
  stage: release
  only:
    - dev
  # don't run release again when merging release back into dev
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\d+.\d+.\d+$/
      - $CI_COMMIT_BEFORE_SHA =~ /^\d+.\d+.\d+$/
      - $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/
      - $CI_COMMIT_TITLE =~ /^\d+.\d+.\d+$/
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm ci
    - git remote add upstream "$UPSTREAM"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - git checkout master
    - git merge origin/dev --no-edit
    - npm run bump
    - git push upstream master
    - git push upstream --tags
    - mv .npmrc-deploy .npmrc
    - npm publish
    - git checkout dev
    # unclear on what these changes are or why they're here post-publish
    - git checkout .
    - git pull --rebase upstream dev
    - git merge master
    - git push --force upstream dev
  tags:
    - docker
