stages:
  - test
  - cover
  - release

test:
  image: node:10
  stage: test
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm ci
    - npm test
  tags:
    - docker
  artifacts:
    paths:
      - coverage

coveralls:
  image: node:10
  dependencies:
    - test
  stage: cover
  only:
    - dev
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\d+.\d+.\d+$/
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm ci
    - npm run coveralls
  tags:
    - docker
  artifacts:
    paths:
      - coverage

release:
  image: node:10
  dependencies:
    - coveralls
  stage: release
  only:
    - dev
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\d+.\d+.\d+$/
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm ci
    - git remote add upstream "$UPSTREAM"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "Justin Livi"
    - git checkout master
    - git merge origin/dev --no-edit
    - npm run bump
    - git push upstream master
    - git push upstream --tags
    - mv .npmrc-deploy .npmrc
    - npm publish
    - git checkout origin/dev
    - git rebase upstream origin/dev
    - git rebase master
    - git push upstream origin/dev
  tags:
    - docker
